---
- name: Restart netbird
  ansible.builtin.systemd:
    name: netbird
    state: restarted
  listen: restart netbird

- name: Install Netbird keyring (dearmor)
  ansible.builtin.command:
    cmd: gpg --dearmor --yes --output {{ netbird_apt_keyring_path }} /tmp/netbird-archive-key.asc
  changed_when: true
  listen: install netbird keyring

- name: Refresh apt cache
  ansible.builtin.apt:
    update_cache: true
  listen: refresh apt cache
